--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Postgres.app)
-- Dumped by pg_dump version 17.5 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END; $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ailment_remedies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ailment_remedies (
    ailment_remedy_id integer NOT NULL,
    ailment_id integer NOT NULL,
    remedy_id integer NOT NULL,
    symptom_description text NOT NULL,
    sort_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: ailment_remedies_ailment_remedy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ailment_remedies ALTER COLUMN ailment_remedy_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ailment_remedies_ailment_remedy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ailments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ailments (
    ailment_id integer NOT NULL,
    ailment_slug text NOT NULL,
    ailment_title text NOT NULL,
    link text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: ailments_ailment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ailments ALTER COLUMN ailment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ailments_ailment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: remedies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.remedies (
    remedy_id integer NOT NULL,
    remedy_name public.citext NOT NULL,
    description text,
    potency text,
    dosage_instructions text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: remedies_remedy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.remedies ALTER COLUMN remedy_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.remedies_remedy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_favorites (
    favorite_id integer NOT NULL,
    user_id integer NOT NULL,
    ailment_id integer,
    remedy_id integer,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    note text,
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT chk_fav_target CHECK (((ailment_id IS NOT NULL) OR (remedy_id IS NOT NULL)))
);


--
-- Name: user_favorites_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_favorites ALTER COLUMN favorite_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_favorites_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    username public.citext NOT NULL,
    email public.citext NOT NULL,
    password_hash text NOT NULL,
    first_name text,
    last_name text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ailment_remedies ailment_remedies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailment_remedies
    ADD CONSTRAINT ailment_remedies_pkey PRIMARY KEY (ailment_remedy_id);


--
-- Name: ailment_remedies ailment_remedies_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailment_remedies
    ADD CONSTRAINT ailment_remedies_unique UNIQUE (ailment_id, remedy_id);


--
-- Name: ailments ailments_ailment_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailments
    ADD CONSTRAINT ailments_ailment_slug_key UNIQUE (ailment_slug);


--
-- Name: ailments ailments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailments
    ADD CONSTRAINT ailments_pkey PRIMARY KEY (ailment_id);


--
-- Name: ailments ailments_slug_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailments
    ADD CONSTRAINT ailments_slug_unique UNIQUE (ailment_slug);


--
-- Name: remedies remedies_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.remedies
    ADD CONSTRAINT remedies_name_unique UNIQUE (remedy_name);


--
-- Name: remedies remedies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.remedies
    ADD CONSTRAINT remedies_pkey PRIMARY KEY (remedy_id);


--
-- Name: ailment_remedies unique_ailment_remedy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailment_remedies
    ADD CONSTRAINT unique_ailment_remedy UNIQUE (ailment_id, remedy_id, symptom_description);


--
-- Name: user_favorites user_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorites
    ADD CONSTRAINT user_favorites_pkey PRIMARY KEY (favorite_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_ailments_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ailments_slug ON public.ailments USING btree (ailment_slug);


--
-- Name: idx_ailments_title; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ailments_title ON public.ailments USING btree (ailment_title);


--
-- Name: idx_ar_ailment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ar_ailment ON public.ailment_remedies USING btree (ailment_id);


--
-- Name: idx_ar_remedy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ar_remedy ON public.ailment_remedies USING btree (remedy_id);


--
-- Name: idx_fav_ailment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fav_ailment ON public.user_favorites USING btree (ailment_id);


--
-- Name: idx_fav_remedy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fav_remedy ON public.user_favorites USING btree (remedy_id);


--
-- Name: idx_fav_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fav_user ON public.user_favorites USING btree (user_id);


--
-- Name: idx_remedies_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_remedies_name ON public.remedies USING btree (remedy_name);


--
-- Name: uniq_ailments_slug_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_ailments_slug_idx ON public.ailments USING btree (ailment_slug);


--
-- Name: ailments trg_ailments_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_ailments_updated_at BEFORE UPDATE ON public.ailments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: remedies trg_remedies_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_remedies_updated_at BEFORE UPDATE ON public.remedies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: users trg_users_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ailment_remedies fk_ar_ailment; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailment_remedies
    ADD CONSTRAINT fk_ar_ailment FOREIGN KEY (ailment_id) REFERENCES public.ailments(ailment_id) ON DELETE CASCADE;


--
-- Name: ailment_remedies fk_ar_remedy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ailment_remedies
    ADD CONSTRAINT fk_ar_remedy FOREIGN KEY (remedy_id) REFERENCES public.remedies(remedy_id) ON DELETE CASCADE;


--
-- Name: user_favorites fk_fav_ailment; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorites
    ADD CONSTRAINT fk_fav_ailment FOREIGN KEY (ailment_id) REFERENCES public.ailments(ailment_id) ON DELETE CASCADE;


--
-- Name: user_favorites fk_fav_remedy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorites
    ADD CONSTRAINT fk_fav_remedy FOREIGN KEY (remedy_id) REFERENCES public.remedies(remedy_id) ON DELETE CASCADE;


--
-- Name: user_favorites fk_fav_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorites
    ADD CONSTRAINT fk_fav_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

